### ISSUE TITLE
发布到npm上后引入。样式不生效

### ISSUE THREAD

**Issue by cjq13415134859** [wforguo/wei-design#2]
为什么引入之后，样式不生效了
<img width="1587" alt="57f1eda0fd8563efaa97adfda2c415a" src="https://user-images.githubusercontent.com/82450738/229714959-fbe6813a-ba09-4073-bcab-e511992cdc14.png">

**Comment by web-farmer** [comment]
> 为什么引入之后，样式不生效了 <img alt="57f1eda0fd8563efaa97adfda2c415a" width="1587" src="https://user-images.githubusercontent.com/82450738/229714959-fbe6813a-ba09-4073-bcab-e511992cdc14.png">

提供下你的npm库和github demo吧

**Comment by cjq13415134859** [comment]
https://gitee.com/chen-cjq/test11.git
npm i cjq-ui

**Comment by web-farmer** [comment]
@cjq13415134859 

  可以去关注下`package.json`中的这几个配置，跟你的打包路径一致之后再试试

```json

  "files": [
        "lib/*",
        "packages/*",
        "Readme.md",
        "package.json"
    ],
    "main": "./lib/web-vue.umd.js",
    "module": "./lib/web-vue.mjs",
    "exports": {
        ".": {
            "import": "./lib/web-vue.mjs",
            "require": "./lib/web-vue.umd.js"
        },
        "./lib/style.css": "./lib/style.css"
    },
```

**Comment by web-farmer** [comment]
@cjq13415134859 

帮忙项目点个star，感谢~
