### ISSUE TITLE
安装完组件之后运行正常，打包报组件库缺少生命

### ISSUE THREAD

**Issue by zhoufeiyue** [wforguo/wei-design#3]
![mmexport1685016702631](https://github.com/wei-design/web-vue/assets/24427637/e6f1f002-fbad-4a20-a7a8-53ad8b51f8d0)

**Comment by zhoufeiyue** [comment]
使用element-plus是不会报错的，可以打包

**Comment by web-farmer** [comment]
> 使用element-plus是不会报错的，可以打包

有没有最小demo，给一个
